name: 'Build bespoke Firedrake Docker container'

on:
  push:
    branches:
      - main
  pull_request:
  # TODO: Make it a cron job rather than running in PR testing

  docker:
    name: 'Build Docker container'
    runs-on: ubuntu-latest
    steps:

      - name: 'Check out the repo'
        uses: actions/checkout@v4

      - name: 'Set up Docker buildx'
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Log into DockerHub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: 'Build and push firedrake-parmmg'
        uses: docker/build-push-action@v5
        with:
          push: true
          no-cache: true
          file: docker/Dockerfile.firedrake
          tags: jwallwork/firedrake-parmmg:latest
